// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nutryon.Infrastructure.Persistence.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "TIPO_REFEICAO",
                columns: table => new {
                    ID_TIPO_REFEICAO = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    NOM_TIPO = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false)
                },
                constraints: table => {
                    table.PrimaryKey("PK_TIPO_REFEICAO", x => x.ID_TIPO_REFEICAO);
                });

            migrationBuilder.CreateTable(
                name: "UNIDADE_MEDIDA",
                columns: table => new {
                    ID_UNIDADE = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    SIGLA = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    DESCR = table.Column<string>(type: "nvarchar(60)", maxLength: 60, nullable: true)
                },
                constraints: table => {
                    table.PrimaryKey("PK_UNIDADE_MEDIDA", x => x.ID_UNIDADE);
                });

            migrationBuilder.CreateTable(
                name: "USUARIO",
                columns: table => new {
                    ID_USUARIO = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    NOM_USUARIO = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    EMAIL = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: false),
                    DtNasc = table.Column<DateTime>(type: "date", nullable: true),
                    DtCriacao = table.Column<DateTime>(type: "date", nullable: false),
                    DtAtualizacao = table.Column<DateTime>(type: "date", nullable: true)
                },
                constraints: table => {
                    table.PrimaryKey("PK_USUARIO", x => x.ID_USUARIO);
                });

            migrationBuilder.CreateTable(
                name: "INGREDIENTE",
                columns: table => new {
                    ID_INGREDIENTE = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    NOM_INGREDIENTE = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: false),
                    IdCategoria = table.Column<long>(type: "bigint", nullable: true),
                    DtCriacao = table.Column<DateTime>(type: "date", nullable: false),
                    DtAtualizacao = table.Column<DateTime>(type: "date", nullable: true)
                },
                constraints: table => {
                    table.PrimaryKey("PK_INGREDIENTE", x => x.ID_INGREDIENTE);
                });

            migrationBuilder.CreateTable(
                name: "REFEICAO",
                columns: table => new {
                    ID_REFEICAO = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ID_USUARIO = table.Column<long>(type: "bigint", nullable: false),
                    ID_TIPO_REFEICAO = table.Column<long>(type: "bigint", nullable: false),
                    DT_REF = table.Column<DateTime>(type: "date", nullable: false),
                    SITUACAO = table.Column<string>(type: "nvarchar(12)", maxLength: 12, nullable: false),
                    OBSERVACAO = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    DtCriacao = table.Column<DateTime>(type: "date", nullable: false),
                    DtAtualizacao = table.Column<DateTime>(type: "date", nullable: true)
                },
                constraints: table => {
                    table.PrimaryKey("PK_REFEICAO", x => x.ID_REFEICAO);
                    table.ForeignKey(
                        name: "FK_REFEICAO_TIPO_REFEICAO_ID_TIPO_REFEICAO",
                        column: x => x.ID_TIPO_REFEICAO,
                        principalTable: "TIPO_REFEICAO",
                        principalColumn: "ID_TIPO_REFEICAO",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_REFEICAO_USUARIO_ID_USUARIO",
                        column: x => x.ID_USUARIO,
                        principalTable: "USUARIO",
                        principalColumn: "ID_USUARIO",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "REFEICAO_ITEM",
                columns: table => new {
                    ID_REFEICAO = table.Column<long>(type: "bigint", nullable: false),
                    ID_INGREDIENTE = table.Column<long>(type: "bigint", nullable: false),
                    QTDE = table.Column<decimal>(type: "decimal(10,3)", precision: 10, scale: 3, nullable: false),
                    ID_UNIDADE = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table => {
                    table.PrimaryKey("PK_REFEICAO_ITEM", x => new { x.ID_REFEICAO, x.ID_INGREDIENTE });
                    table.ForeignKey(
                        name: "FK_REFEICAO_ITEM_INGREDIENTE_ID_INGREDIENTE",
                        column: x => x.ID_INGREDIENTE,
                        principalTable: "INGREDIENTE",
                        principalColumn: "ID_INGREDIENTE",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_REFEICAO_ITEM_REFEICAO_ID_REFEICAO",
                        column: x => x.ID_REFEICAO,
                        principalTable: "REFEICAO",
                        principalColumn: "ID_REFEICAO",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_REFEICAO_ITEM_UNIDADE_MEDIDA_ID_UNIDADE",
                        column: x => x.ID_UNIDADE,
                        principalTable: "UNIDADE_MEDIDA",
                        principalColumn: "ID_UNIDADE",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_USUARIO_EMAIL",
                table: "USUARIO",
                column: "EMAIL",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_REFEICAO_ID_TIPO_REFEICAO",
                table: "REFEICAO",
                column: "ID_TIPO_REFEICAO");

            migrationBuilder.CreateIndex(
                name: "IX_REFEICAO_ID_USUARIO",
                table: "REFEICAO",
                column: "ID_USUARIO");

            migrationBuilder.CreateIndex(
                name: "IX_REFEICAO_ITEM_ID_INGREDIENTE",
                table: "REFEICAO_ITEM",
                column: "ID_INGREDIENTE");

            migrationBuilder.CreateIndex(
                name: "IX_REFEICAO_ITEM_ID_UNIDADE",
                table: "REFEICAO_ITEM",
                column: "ID_UNIDADE");

            migrationBuilder.InsertData(
                table: "TIPO_REFEICAO",
                columns: new[] { "ID_TIPO_REFEICAO", "NOM_TIPO" },
                values: new object[,] { {1L, "Café da manhã"}, {2L, "Almoço"}, {3L, "Jantar"} });

            migrationBuilder.InsertData(
                table: "UNIDADE_MEDIDA",
                columns: new[] { "ID_UNIDADE", "SIGLA", "DESCR" },
                values: new object[,] { {1L, "g", "grama"}, {2L, "ml", "mililitro"} });

            migrationBuilder.InsertData(
                table: "INGREDIENTE",
                columns: new[] { "ID_INGREDIENTE", "NOM_INGREDIENTE", "IdCategoria", "DtCriacao", "DtAtualizacao" },
                values: new object[,] {
                    {1L, "Arroz", null, DateTime.UtcNow.Date, null},
                    {2L, "Feijão", null, DateTime.UtcNow.Date, null},
                    {3L, "Frango", null, DateTime.UtcNow.Date, null}
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "REFEICAO_ITEM");
            migrationBuilder.DropTable(name: "INGREDIENTE");
            migrationBuilder.DropTable(name: "REFEICAO");
            migrationBuilder.DropTable(name: "UNIDADE_MEDIDA");
            migrationBuilder.DropTable(name: "TIPO_REFEICAO");
            migrationBuilder.DropTable(name: "USUARIO");
        }
    }
}