// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutryon.Infrastructure.Persistence;

#nullable disable

namespace Nutryon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NutryonDbContext))]
    partial class NutryonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // Removed provider-specific: UseIdentityColumns for SQL Server

            modelBuilder.Entity("Nutryon.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<long>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_INGREDIENTE");
                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("date");

                    b.Property<long?>("IdCategoria")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeIngrediente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("NOM_INGREDIENTE");

                    b.ToTable("INGREDIENTE", (string)null);

                    b.HasData(
                        new
                        {
                            IdIngrediente = 1L,
                            DtCriacao = DateTime.SpecifyKind(DateTime.UtcNow.Date, DateTimeKind.Unspecified),
                            NomeIngrediente = "Arroz"
                        },
                        new
                        {
                            IdIngrediente = 2L,
                            DtCriacao = DateTime.SpecifyKind(DateTime.UtcNow.Date, DateTimeKind.Unspecified),
                            NomeIngrediente = "Feijão"
                        },
                        new
                        {
                            IdIngrediente = 3L,
                            DtCriacao = DateTime.SpecifyKind(DateTime.UtcNow.Date, DateTimeKind.Unspecified),
                            NomeIngrediente = "Frango"
                        });
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.Refeicao", b =>
                {
                    b.Property<long>("IdRefeicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_REFEICAO");
                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("date");

                    b.Property<DateTime>("DtRef")
                        .HasColumnType("date")
                        .HasColumnName("DT_REF");

                    b.Property<long>("IdTipoRefeicao")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_TIPO_REFEICAO");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("SITUACAO");

                    b.ToTable("REFEICAO", (string)null);
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.RefeicaoItem", b =>
                {
                    b.Property<long>("IdRefeicao")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_REFEICAO");

                    b.Property<long>("IdIngrediente")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_INGREDIENTE");

                    b.Property<long>("IdUnidade")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_UNIDADE");

                    b.Property<decimal>("Qtde")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("QTDE");

                    b.HasKey("IdRefeicao", "IdIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.HasIndex("IdUnidade");

                    b.ToTable("REFEICAO_ITEM", (string)null);
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.TipoRefeicao", b =>
                {
                    b.Property<long>("IdTipoRefeicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_TIPO_REFEICAO");
                    b.Property<string>("NomeTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOM_TIPO");

                    b.ToTable("TIPO_REFEICAO", (string)null);

                    b.HasData(
                        new { IdTipoRefeicao = 1L, NomeTipo = "Café da manhã" },
                        new { IdTipoRefeicao = 2L, NomeTipo = "Almoço" },
                        new { IdTipoRefeicao = 3L, NomeTipo = "Jantar" });
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.UnidadeMedida", b =>
                {
                    b.Property<long>("IdUnidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_UNIDADE");
                    b.Property<string>("Descr")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("DESCR");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SIGLA");

                    b.ToTable("UNIDADE_MEDIDA", (string)null);

                    b.HasData(
                        new { IdUnidade = 1L, Sigla = "g", Descr = "grama" },
                        new { IdUnidade = 2L, Sigla = "ml", Descr = "mililitro" });
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_USUARIO");
                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("date");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DtNasc")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOM_USUARIO");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USUARIO_EMAIL");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.Refeicao", b =>
                {
                    b.HasOne("Nutryon.Domain.Entities.TipoRefeicao", "Tipo")
                        .WithMany()
                        .HasForeignKey("IdTipoRefeicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutryon.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Refeicoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.RefeicaoItem", b =>
                {
                    b.HasOne("Nutryon.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany("Itens")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutryon.Domain.Entities.Refeicao", "Refeicao")
                        .WithMany("Itens")
                        .HasForeignKey("IdRefeicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutryon.Domain.Entities.UnidadeMedida", "Unidade")
                        .WithMany()
                        .HasForeignKey("IdUnidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Refeicao");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.Ingrediente", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.Refeicao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Nutryon.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Refeicoes");
                });
#pragma warning restore 612, 618
        }
    }
}